/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class analizador extends javax.swing.JPanel {

    /**
     * Creates new form analizador
     */
    public analizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavbar = new javax.swing.JPanel();
        btnExportar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblTituloAnalizador = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        panelCodigo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputCodigo = new javax.swing.JTextArea();
        btnLimpiar = new javax.swing.JButton();
        btnVerificar = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavbar.setBackground(new java.awt.Color(255, 255, 255));
        panelNavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExportar.setBackground(new java.awt.Color(0, 54, 105));
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        panelNavbar.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 120, 30));

        btnRegresar.setText("Ir a inicio");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelNavbar.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 110, 30));

        lblTituloAnalizador.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblTituloAnalizador.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAnalizador.setText("Analizador");
        panelNavbar.add(lblTituloAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        lblLogo.setText("Logo_OnRev");
        panelNavbar.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        add(panelNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        panelCodigo.setBackground(new java.awt.Color(255, 255, 255));
        panelCodigo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Pseudocódigo");
        panelCodigo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        inputCodigo.setColumns(20);
        inputCodigo.setFont(new java.awt.Font("Consolas", 0, 16)); // NOI18N
        inputCodigo.setRows(5);
        inputCodigo.setTabSize(2);
        inputCodigo.setText("Coloca tu algoritmo oLoop");
        jScrollPane1.setViewportView(inputCodigo);

        panelCodigo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 500));

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 54, 105));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 54, 105), 1, true));
        panelCodigo.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 300, 40));

        btnVerificar.setBackground(new java.awt.Color(0, 54, 105));
        btnVerificar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerificar.setForeground(new java.awt.Color(255, 255, 255));
        btnVerificar.setText("Verificar");
        btnVerificar.setBorder(null);
        panelCodigo.add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 300, 40));

        add(panelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, 700));

        panelResultados.setBackground(new java.awt.Color(255, 255, 255));
        panelResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Aún no se procesa ningún algoritmo.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(297, 297, 297))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel3)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        panelResultados.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 930, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Gráfica de la función de tiempo teórica");
        panelResultados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Función de tiempo");
        panelResultados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 570, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setText("Complejidad Algoritmica");
        panelResultados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("ns");
        panelResultados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 610, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("ns");
        panelResultados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, -1, -1));

        add(panelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 1010, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JTextArea inputCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloAnalizador;
    private javax.swing.JPanel panelCodigo;
    private javax.swing.JPanel panelNavbar;
    private javax.swing.JPanel panelResultados;
    // End of variables declaration//GEN-END:variables
}
