/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Usuario
 */
public class frmComparador extends javax.swing.JPanel {

    /**
     * Creates new form comparador
     */
    public frmComparador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavbar = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTituloAnalizador = new javax.swing.JLabel();
        btnExportar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        panelComparacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelFReal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelFTeorica = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblValorComplejidad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblValorTiempoEjecucion = new javax.swing.JLabel();
        panelAlgoritmos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxAlgoritmos = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputInfoAlgoritmos = new javax.swing.JTextArea();
        btnComparar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavbar.setBackground(new java.awt.Color(255, 255, 255));
        panelNavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setText("Logo_OnRev");
        panelNavbar.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblTituloAnalizador.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        lblTituloAnalizador.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAnalizador.setText("Comparador");
        panelNavbar.add(lblTituloAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        btnExportar.setBackground(new java.awt.Color(0, 54, 105));
        btnExportar.setForeground(new java.awt.Color(255, 255, 255));
        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });
        panelNavbar.add(btnExportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 120, 30));

        btnRegresar.setText("Ir a inicio");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelNavbar.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 110, 30));

        add(panelNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        panelComparacion.setBackground(new java.awt.Color(255, 255, 255));
        panelComparacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Comparación de las gráficas");
        panelComparacion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Función de tiempo real");

        javax.swing.GroupLayout panelFRealLayout = new javax.swing.GroupLayout(panelFReal);
        panelFReal.setLayout(panelFRealLayout);
        panelFRealLayout.setHorizontalGroup(
            panelFRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFRealLayout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(138, 138, 138))
        );
        panelFRealLayout.setVerticalGroup(
            panelFRealLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFRealLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel3)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        panelComparacion.add(panelFReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 450, 500));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Función de tiempo teórica");

        javax.swing.GroupLayout panelFTeoricaLayout = new javax.swing.GroupLayout(panelFTeorica);
        panelFTeorica.setLayout(panelFTeoricaLayout);
        panelFTeoricaLayout.setHorizontalGroup(
            panelFTeoricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFTeoricaLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(132, 132, 132))
        );
        panelFTeoricaLayout.setVerticalGroup(
            panelFTeoricaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFTeoricaLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jLabel8)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        panelComparacion.add(panelFTeorica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 450, 500));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setText("Complejidad Algoritmica");
        panelComparacion.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        lblValorComplejidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorComplejidad.setText("ns");
        panelComparacion.add(lblValorComplejidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Tiempo de ejecución");
        panelComparacion.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, -1, -1));

        lblValorTiempoEjecucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTiempoEjecucion.setText("ns");
        panelComparacion.add(lblValorTiempoEjecucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 610, -1, -1));

        add(panelComparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 1010, 700));

        panelAlgoritmos.setBackground(new java.awt.Color(255, 255, 255));
        panelAlgoritmos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Algoritmos predefinidos");
        panelAlgoritmos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        comboBoxAlgoritmos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboBoxAlgoritmos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QuickSort", "MergeSort" }));
        panelAlgoritmos.add(comboBoxAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 300, 30));

        inputInfoAlgoritmos.setEditable(false);
        inputInfoAlgoritmos.setColumns(20);
        inputInfoAlgoritmos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        inputInfoAlgoritmos.setForeground(new java.awt.Color(153, 153, 153));
        inputInfoAlgoritmos.setRows(5);
        inputInfoAlgoritmos.setTabSize(2);
        inputInfoAlgoritmos.setText("Se mostrará información referente al algoritmo que se eliga.");
        inputInfoAlgoritmos.setWrapStyleWord(true);
        inputInfoAlgoritmos.setEnabled(false);
        inputInfoAlgoritmos.setFocusable(false);
        jScrollPane1.setViewportView(inputInfoAlgoritmos);

        panelAlgoritmos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 300, 440));

        btnComparar.setBackground(new java.awt.Color(0, 54, 105));
        btnComparar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnComparar.setForeground(new java.awt.Color(255, 255, 255));
        btnComparar.setText("Comparar");
        btnComparar.setBorder(null);
        panelAlgoritmos.add(btnComparar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 300, 40));

        add(panelAlgoritmos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 360, 700));
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComparar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboBoxAlgoritmos;
    private javax.swing.JTextArea inputInfoAlgoritmos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTituloAnalizador;
    private javax.swing.JLabel lblValorComplejidad;
    private javax.swing.JLabel lblValorTiempoEjecucion;
    private javax.swing.JPanel panelAlgoritmos;
    private javax.swing.JPanel panelComparacion;
    private javax.swing.JPanel panelFReal;
    private javax.swing.JPanel panelFTeorica;
    private javax.swing.JPanel panelNavbar;
    // End of variables declaration//GEN-END:variables
}
