/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Usuario
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        lblDescripcion = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnAnalizador = new javax.swing.JButton();
        btnComparador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(255, 255, 255));
        panelHome.setMinimumSize(new java.awt.Dimension(1280, 768));
        panelHome.setPreferredSize(new java.awt.Dimension(1280, 768));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setPreferredSize(new java.awt.Dimension(1280, 768));
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDescripcion.setText("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam convallis gravida accumsan. Vestibulum lacus nulla, volutpat molestie fringilla at, porta ut leo.");
        panelContenido.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));
        lblDescripcion.getAccessibleContext().setAccessibleDescription("");

        lblTitulo.setFont(new java.awt.Font("Cambria Math", 1, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("OnRev");
        panelContenido.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        btnAnalizador.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnAnalizador.setText("Analizador");
        btnAnalizador.setToolTipText("");
        btnAnalizador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizadorActionPerformed(evt);
            }
        });
        panelContenido.add(btnAnalizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        btnComparador.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnComparador.setText("Comparador");
        btnComparador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComparador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComparadorActionPerformed(evt);
            }
        });
        panelContenido.add(btnComparador, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 470, -1, -1));

        panelHome.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        getContentPane().add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalizadorActionPerformed

    private void btnComparadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComparadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComparadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnalizador;
    public javax.swing.JButton btnComparador;
    public javax.swing.JLabel lblDescripcion;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JPanel panelContenido;
    public javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
}
